name: "allcheckspassed"
description: "GitHub Action to check if all checks have passed on a specific commit"
author: "wechuli"
branding:
  icon: "check-circle"
  color: "green"
inputs:
  commit_sha:
    description: "The commit sha that you want to check"
    required: false
  token:
    description: "The GitHub token to use for authentication"
    required: false
    default: ${{ github.token }}
  checks_include:
    description: "A comma separated list of checks to include in the evaluation, by default, all checks are included. You can provide a list of map keys, with app_id and check_name, to include only checks from a specific app, or with a specific name. Supports regex"
    required: false
    default: "-1"
  checks_exclude:
    description: "A comma separated list of checks to exclude, if these checks fail,the action will not fail"
    required: false
    default: "-1"
  treat_skipped_as_passed:
    description: "If set to true, skipped checks will be treated as passed"
    required: false
    default: "true"
  treat_neutral_as_passed:
    description: "If set to true, neutral checks will be treated as passed"
    required: false
    default: "true"
  poll:
    description: "Whether to poll the API for completed checks or to simply check once and exit"
    required: false
    default: "true"
  delay:
    description: "The period in minutes to wait to allow the checks to complete"
    required: false
    default: "1"
  polling_interval:
    description: "The period in minutes between API calls that polls the GitHub Api for completed checks, shorter intervals may result in API rate limiting"
    required: false
    default: "1"
  retries:
    description: "The number of times to retry the API call to get the checks, if the API call fails"
    required: false
    default: "10"
  fail_fast:
    description: "If set to true, the action will fail the step as soon as a single conditions for failure is met, defaults to false. Can be used to terminate the action early if failure occur quickly while other checks run long."
    required: false
    default: "false"
  fail_step:
    description: "If set to true, the action will fail the step if the conditions for failure are met, defaults to true. Be careful with this option if you have configured rulesets/branch protection rules that require all checks to pass before merging"
    required: false
    default: "true"
  fail_on_missing_checks:
    description: "If set to true, the action will fail if one or more checks defined on the checks_include input are not found on the commit"
    required: false
    default: "false"

outputs:
  checks:
    description: "List of checks that were evaluated"
  missing_checks:
    description: "List of checks that were not found on the commit"


runs:
  using: node20
  main: dist/index.js
