name: Build Action
on:
  push:
    branches:
      - "main"
    paths:
      - "src/**"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "24.4.0"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      # - name: Test Action
      #   run: npm run test
      - name: Build Action
        run: npm run build
      - name: Package Action
        run: npm run package
      - name: Commit and push
        env:
          ACTOR: ${{ github.actor }}
        run: |
          git config --global user.name "$ACTOR"
          git config --global user.email "$ACTOR@users.noreply.github.com"
          git add .
          git commit -m "Action build at commit $GITHUB_SHA"
          git push origin
